kumuluzee:
  name: carts-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:3002
    http:
      port: 3002
  config:
    consul:
      agent: http://35.196.140.237

rest-properties:
  maintenance-mode: false
  broken: false
  catalogue-url: http://localhost:3002